version: 1.1.6.{build}

install:
    - nuget restore

build:
  project: fluentOptionals.sln
  verbosity: detailed
  publish_nuget: true

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

deploy:
  provider: NuGet
  api_key:
    secure: cN/5QbdaICN1YRrkT4atFVJh9herFrwY7zE6XXWCASecAzW5QnMegvq7p4eDRh5f
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    appveor_repo_tag: true

environment:
    COVERALLS_REPO_TOKEN:  
       secure: jLz7jnb3ocqE8cxrWdbDQRcl+OchEBHc/3jn5H2/eKUptxiFDqptR3YiwOmUCfmV

after_test: 
  - cmd: packages\OpenCover.4.6.166\tools\OpenCover.Console.exe -register:user -filter:"+[*]* -[FluentAssertions*]*" -target:"packages\NUnit.ConsoleRunner.3.4.1\tools\nunit3-console.exe" -targetargs:"/domain:single fluentOptionals.Tests/bin/debug/fluentOptionals.Tests.dll" -output:coverage.xml
  - cmd: packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
